// No-op definitions of the two Intel TBB runtime entry points that Stan math
// instantiates through headers, for WebAssembly/webR builds only.
//
// Why they are needed
// -------------------
// Every reverse-mode AD translation unit of Stan math includes
// `stan/math/rev/core/init_chainablestack.hpp`, which defines
//
//     class ad_tape_observer final : public tbb::task_scheduler_observer {
//       ad_tape_observer() { observe(true); }        // -> tbb::detail::r1::observe
//       ~ad_tape_observer() { observe(false); }
//     };
//     namespace { ad_tape_observer global_observer; }
//
// unconditionally, at namespace scope. `stan/math/rev/core/profiling.hpp`
// likewise holds the profile map in a `tbb::concurrent_unordered_map` over
// `tbb_allocator`. Neither is guarded by `RCPP_PARALLEL_USE_TBB`, so the
// resulting objects import
//
//     _ZN3tbb6detail2r17observeERNS0_2d123task_scheduler_observerEb
//         tbb::detail::r1::observe(tbb::detail::d1::task_scheduler_observer&, bool)
//     _ZN3tbb6detail2r117deallocate_memoryEPv
//         tbb::detail::r1::deallocate_memory(void*)
//
// even with an empty link line. Nothing in the wasm ecosystem provides them:
// `repo.r-wasm.org`'s RcppParallel is a 575-byte stub built with TBB disabled,
// and its bundled oneTBB cannot currently be cross-compiled under emscripten
// (r-wasm/webr#427). All other `tbb::detail::d1::*` symbols the modules import
// are header-defined weak symbols that the same module also exports, so they
// self-resolve; these two are the only genuine runtime entry points.
//
// Because `global_observer` is a global, its constructor runs while the module
// is being loaded, so the missing symbols surface as a `dlopen()` failure
// ("unable to load shared object '.../rstan.so'"), not as a runtime error.
//
// Every module needs its own copy
// -------------------------------
// R loads package DLLs with `dyn.load(local = TRUE)`, i.e. `RTLD_LOCAL`, and
// webR's Emscripten loader gives every such module a private symbol scope
// (`localScope = global ? null : {}`): a module resolves its imports against
// the main module's table, its own private scope, and its own exports -- never
// against another package's DLL. So `rstan` cannot supply these to `RBesT`,
// nor the other way round. This single file is therefore compiled into both:
//
//   * into `RBesT` itself -- `configure` copies it to `src/webr-tbb-stubs.cpp`
//     (`src/` is generated by `rstantools::rstan_config()`, so it cannot be
//     kept there);
//   * into `rstan` -- `tools/webr/patch-rstan-tarball.R` adds it to the rstan
//     source tarball's `src/` before either wasm build route cross-compiles
//     it, because the published wasm `rstan` binary cannot be loaded at all.
//
// Why the no-ops are safe
// -----------------------
// webR is single-threaded: `parallel::detectCores()` is NA and `cores` must be
// 1. `ad_tape_observer` exists only to give TBB *worker* threads their own
// `ChainableStack`; the main thread's stack comes from the static initialiser
// in `ChainableStack::AutodiffStackStorage`. With no TBB scheduler there are no
// worker threads to observe, so an `observe()` that does nothing is exactly
// right. The profiling map stays empty unless Stan profiling is switched on,
// and `tbb_allocator` obtains its memory from the ordinary allocator, so
// `free()` is the correct counterpart to it.
//
// This is a stopgap. The real fix is upstream: `global_observer` should not be
// instantiated when there is no TBB runtime. See
// design/howto-build-rbest-webr.md section 9.
//
// `#ifdef __EMSCRIPTEN__` keeps every native build -- where TBB is real and
// these symbols must come from the actual runtime -- entirely unaffected.
//
// The declarations below are deliberately minimal: `task_scheduler_observer` is
// only ever named through a reference, so an incomplete type is enough and no
// TBB header is required. What matters is that the mangled names match exactly;
// `nm` on the compiled object is the check, and
// `tools/webr/wasm-tbb-symbols.cjs` is the check on the finished image.

#ifdef __EMSCRIPTEN__

#include <stdlib.h>

namespace tbb {
namespace detail {

namespace d1 {
class task_scheduler_observer;
}

namespace r1 {

void observe(d1::task_scheduler_observer&, bool) {}

void deallocate_memory(void* p) { free(p); }

}  // namespace r1
}  // namespace detail
}  // namespace tbb

#else

// Keeps this a non-empty translation unit on every other platform.
namespace rbest_webr_tbb_stubs {}

#endif  // __EMSCRIPTEN__
