##
## Shared helpers for the WebAssembly TBB stub patch.
##
## The wasm build has to make `rstan`'s wasm binary define the two Intel TBB
## runtime entry points that Stan math imports through headers (see
## inst/webr/tbb-stubs.cpp and design/howto-build-rbest-webr.md section 9):
## tools/webr/patch-rstan-tarball.R adds the stub to rstan's `src/` and rstan is
## cross-compiled from there.
##
## These helpers are the bookkeeping around it: the patch must be explicit,
## logged, and recorded in the shipped artefact, so that the wasm rstan is never
## mistaken for a stock build of the same version. They live here, one directory
## above tools/webr/docker, because the docker build context cannot reach out of
## itself -- compose.yaml passes them in through the `webrtools` build context.
##

## sha256 of a file. `tools::sha256sum()` is recent, so fall back to the system
## utility, and finally to md5 -- labelled as such, since an unlabelled digest
## of unknown algorithm is worse than no digest.
webr_checksum <- function(path) {
  if (exists("sha256sum", envir = asNamespace("tools"))) {
    return(paste0("sha256:", unname(getExportedValue("tools", "sha256sum")(path))))
  }
  for (prog in c("sha256sum", "shasum")) {
    exe <- Sys.which(prog)
    if (nzchar(exe)) {
      out <- tryCatch(
        system2(exe, c(if (prog == "shasum") "-a256", shQuote(path)), stdout = TRUE),
        error = function(e) character()
      )
      if (length(out)) {
        return(paste0("sha256:", sub("[[:space:]].*$", "", out[1])))
      }
    }
  }
  paste0("md5:", unname(tools::md5sum(path)))
}

## The single copy of the stub source, from a package root. It lives under
## `inst/` rather than in `tools/` because `src/` is generated by
## `rstantools::rstan_config()` and `tools/` is .Rbuildignore'd: `inst/webr/`
## is the one place that is both tracked and present in a staged source
## package, which is what `configure` and the build script read it from.
webr_stub_source <- function(root = ".") {
  path <- file.path(root, "inst", "webr", "tbb-stubs.cpp")
  if (!file.exists(path)) {
    stop("the TBB stub source is missing: ", path)
  }
  path
}

## A human-readable record of what was patched, written next to the image and
## shipped with it. Deliberately plain text: it is meant to be read by whoever
## finds the artefact, not parsed.
##
## `entries` is a list of named character vectors, one per patched package.
webr_write_patch_manifest <- function(dir, entries, stub_file) {
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  path <- file.path(dir, "PATCHES.txt")
  lines <- c(
    "RBesT webR library image -- applied patches",
    "",
    "The packages listed below are NOT stock builds of the versions they",
    "report. They were modified during the wasm build. See",
    "design/howto-build-rbest-webr.md section 9 for the rationale.",
    "",
    "RBesT itself is unmodified: its own inst/webr/tbb-stubs.cpp carries the",
    "same definitions, guarded by `#ifdef __EMSCRIPTEN__`, and is part of the",
    "released sources.",
    "",
    paste("generated:", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z")),
    ""
  )
  for (entry in entries) {
    lines <- c(lines, paste0(names(entry), ": ", unname(entry)), "")
  }
  lines <- c(
    lines,
    "--- inst/webr/tbb-stubs.cpp ---------------------------------------",
    readLines(stub_file, warn = FALSE)
  )
  writeLines(lines, path)
  message("== wrote ", path, " ==")
  path
}
